"""baseline schema

Revision ID: cc98fe3c87aa
Revises: 
Create Date: 2025-09-14 20:47:27.744316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc98fe3c87aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique alliance identifier'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique alliance name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alliances_name'), 'alliances', ['name'], unique=True)
    op.create_table('wars',
    sa.Column('war_id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique war identifier'),
    sa.Column('alliance_id', sa.Integer(), nullable=False, comment='Reference to participating alliance'),
    sa.Column('war_enemy_name', sa.String(length=255), nullable=False, comment='Name of the enemy alliance'),
    sa.Column('attack_seq_counter', sa.Integer(), nullable=False, comment='Global attack sequence counter for this war'),
    sa.Column('defence_seq_counter', sa.Integer(), nullable=False, comment='Global defense sequence counter for this war'),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.PrimaryKeyConstraint('war_id')
    )
    op.create_index(op.f('ix_wars_alliance_id'), 'wars', ['alliance_id'], unique=False)
    op.create_table('players',
    sa.Column('gamer_id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique player identifier'),
    sa.Column('name_folder', sa.String(length=1024), nullable=False, comment='Player name or folder identifier'),
    sa.Column('alliance_id', sa.Integer(), nullable=False, comment="Reference to player's alliance"),
    sa.Column('war_id', sa.Integer(), nullable=False, comment='Reference to the war this player participates in'),
    sa.Column('base_hp', sa.Integer(), nullable=True, comment="Player's base hit points for damage calculations"),
    sa.Column('attack_1', sa.Integer(), nullable=True, comment='Damage in attack slot 1'),
    sa.Column('attack_1_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for attack 1'),
    sa.Column('attack_1_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for attack 1'),
    sa.Column('attack_2', sa.Integer(), nullable=True, comment='Damage in attack slot 2'),
    sa.Column('attack_2_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for attack 2'),
    sa.Column('attack_2_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for attack 2'),
    sa.Column('attack_3', sa.Integer(), nullable=True, comment='Damage in attack slot 3'),
    sa.Column('attack_3_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for attack 3'),
    sa.Column('attack_3_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for attack 3'),
    sa.Column('attack_4', sa.Integer(), nullable=True, comment='Damage in attack slot 4'),
    sa.Column('attack_4_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for attack 4'),
    sa.Column('attack_4_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for attack 4'),
    sa.Column('attack_5', sa.Integer(), nullable=True, comment='Damage in attack slot 5'),
    sa.Column('attack_5_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for attack 5'),
    sa.Column('attack_5_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for attack 5'),
    sa.Column('attack_6', sa.Integer(), nullable=True, comment='Damage in attack slot 6'),
    sa.Column('attack_6_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for attack 6'),
    sa.Column('attack_6_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for attack 6'),
    sa.Column('defence_1', sa.Integer(), nullable=True, comment='Damage received in defense slot 1'),
    sa.Column('defence_1_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 1'),
    sa.Column('defence_1_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 1'),
    sa.Column('defence_2', sa.Integer(), nullable=True, comment='Damage received in defense slot 2'),
    sa.Column('defence_2_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 2'),
    sa.Column('defence_2_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 2'),
    sa.Column('defence_3', sa.Integer(), nullable=True, comment='Damage received in defense slot 3'),
    sa.Column('defence_3_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 3'),
    sa.Column('defence_3_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 3'),
    sa.Column('defence_4', sa.Integer(), nullable=True, comment='Damage received in defense slot 4'),
    sa.Column('defence_4_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 4'),
    sa.Column('defence_4_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 4'),
    sa.Column('defence_5', sa.Integer(), nullable=True, comment='Damage received in defense slot 5'),
    sa.Column('defence_5_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 5'),
    sa.Column('defence_5_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 5'),
    sa.Column('defence_6', sa.Integer(), nullable=True, comment='Damage received in defense slot 6'),
    sa.Column('defence_6_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 6'),
    sa.Column('defence_6_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 6'),
    sa.Column('defence_7', sa.Integer(), nullable=True, comment='Damage received in defense slot 7'),
    sa.Column('defence_7_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 7'),
    sa.Column('defence_7_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 7'),
    sa.Column('defence_8', sa.Integer(), nullable=True, comment='Damage received in defense slot 8'),
    sa.Column('defence_8_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 8'),
    sa.Column('defence_8_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 8'),
    sa.Column('defence_9', sa.Integer(), nullable=True, comment='Damage received in defense slot 9'),
    sa.Column('defence_9_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 9'),
    sa.Column('defence_9_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 9'),
    sa.Column('defence_10', sa.Integer(), nullable=True, comment='Damage received in defense slot 10'),
    sa.Column('defence_10_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 10'),
    sa.Column('defence_10_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 10'),
    sa.Column('defence_11', sa.Integer(), nullable=True, comment='Damage received in defense slot 11'),
    sa.Column('defence_11_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 11'),
    sa.Column('defence_11_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 11'),
    sa.Column('defence_12', sa.Integer(), nullable=True, comment='Damage received in defense slot 12'),
    sa.Column('defence_12_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 12'),
    sa.Column('defence_12_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 12'),
    sa.Column('defence_13', sa.Integer(), nullable=True, comment='Damage received in defense slot 13'),
    sa.Column('defence_13_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 13'),
    sa.Column('defence_13_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 13'),
    sa.Column('defence_14', sa.Integer(), nullable=True, comment='Damage received in defense slot 14'),
    sa.Column('defence_14_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 14'),
    sa.Column('defence_14_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 14'),
    sa.Column('defence_15', sa.Integer(), nullable=True, comment='Damage received in defense slot 15'),
    sa.Column('defence_15_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 15'),
    sa.Column('defence_15_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 15'),
    sa.Column('defence_16', sa.Integer(), nullable=True, comment='Damage received in defense slot 16'),
    sa.Column('defence_16_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 16'),
    sa.Column('defence_16_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 16'),
    sa.Column('defence_17', sa.Integer(), nullable=True, comment='Damage received in defense slot 17'),
    sa.Column('defence_17_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 17'),
    sa.Column('defence_17_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 17'),
    sa.Column('defence_18', sa.Integer(), nullable=True, comment='Damage received in defense slot 18'),
    sa.Column('defence_18_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 18'),
    sa.Column('defence_18_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 18'),
    sa.Column('defence_19', sa.Integer(), nullable=True, comment='Damage received in defense slot 19'),
    sa.Column('defence_19_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 19'),
    sa.Column('defence_19_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 19'),
    sa.Column('defence_20', sa.Integer(), nullable=True, comment='Damage received in defense slot 20'),
    sa.Column('defence_20_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 20'),
    sa.Column('defence_20_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 20'),
    sa.Column('defence_21', sa.Integer(), nullable=True, comment='Damage received in defense slot 21'),
    sa.Column('defence_21_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 21'),
    sa.Column('defence_21_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 21'),
    sa.Column('defence_22', sa.Integer(), nullable=True, comment='Damage received in defense slot 22'),
    sa.Column('defence_22_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 22'),
    sa.Column('defence_22_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 22'),
    sa.Column('defence_23', sa.Integer(), nullable=True, comment='Damage received in defense slot 23'),
    sa.Column('defence_23_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 23'),
    sa.Column('defence_23_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 23'),
    sa.Column('defence_24', sa.Integer(), nullable=True, comment='Damage received in defense slot 24'),
    sa.Column('defence_24_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 24'),
    sa.Column('defence_24_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 24'),
    sa.Column('defence_25', sa.Integer(), nullable=True, comment='Damage received in defense slot 25'),
    sa.Column('defence_25_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 25'),
    sa.Column('defence_25_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 25'),
    sa.Column('defence_26', sa.Integer(), nullable=True, comment='Damage received in defense slot 26'),
    sa.Column('defence_26_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 26'),
    sa.Column('defence_26_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 26'),
    sa.Column('defence_27', sa.Integer(), nullable=True, comment='Damage received in defense slot 27'),
    sa.Column('defence_27_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 27'),
    sa.Column('defence_27_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 27'),
    sa.Column('defence_28', sa.Integer(), nullable=True, comment='Damage received in defense slot 28'),
    sa.Column('defence_28_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 28'),
    sa.Column('defence_28_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 28'),
    sa.Column('defence_29', sa.Integer(), nullable=True, comment='Damage received in defense slot 29'),
    sa.Column('defence_29_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 29'),
    sa.Column('defence_29_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 29'),
    sa.Column('defence_30', sa.Integer(), nullable=True, comment='Damage received in defense slot 30'),
    sa.Column('defence_30_sc_id', sa.Integer(), nullable=True, comment='Screenshot crop ID for defense 30'),
    sa.Column('defence_30_sec_id', sa.Integer(), nullable=True, comment='Sequence ID for defense 30'),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['wars.war_id'], ),
    sa.PrimaryKeyConstraint('gamer_id')
    )
    op.create_index(op.f('ix_players_alliance_id'), 'players', ['alliance_id'], unique=False)
    op.create_index(op.f('ix_players_war_id'), 'players', ['war_id'], unique=False)
    op.create_table('screenshots',
    sa.Column('screen_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['war_id'], ['wars.war_id'], ),
    sa.PrimaryKeyConstraint('screen_id')
    )
    op.create_index(op.f('ix_screenshots_war_id'), 'screenshots', ['war_id'], unique=False)
    op.create_table('screenshot_crops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('row_idx', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screenshots.screen_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['war_id'], ['wars.war_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screenshot_crops')
    op.drop_index(op.f('ix_screenshots_war_id'), table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_players_war_id'), table_name='players')
    op.drop_index(op.f('ix_players_alliance_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_wars_alliance_id'), table_name='wars')
    op.drop_table('wars')
    op.drop_index(op.f('ix_alliances_name'), table_name='alliances')
    op.drop_table('alliances')
    # ### end Alembic commands ###
