/**
 * Build a static URL to the debug image generated by the backend:
 *   /static/debug_seg_dark/w{screenId}/debug.png
 *
 * We derive the server origin from API_BASE (e.g., http://localhost:8000/api -> http://localhost:8000).
 */
export function buildDebugUrl(screenId: number, apiBase: string): string {
  if (!Number.isFinite(screenId) || screenId <= 0) return "";
  try {
    const u = new URL(apiBase);
    const origin = `${u.protocol}//${u.host}`;
    return `${origin}/static/debug_seg_dark/w${screenId}/debug.png`;
  } catch {
    // Fallback: if API_BASE is malformed, still return a relative path.
    return `/static/debug_seg_dark/w${screenId}/debug.png`;
  }
}

/** Add a cache-busting query param to ensure the browser fetches a fresh image. */
export function bust(url: string): string {
  if (!url) return url;
  const sep = url.includes("?") ? "&" : "?";
  return `${url}${sep}v=${Date.now()}`;
}
